IgnoreURLs:
  - .*localhost.*
  - https://expedia.com
  - https://github.com/linkerd/website/edit/master/linkerd.io/content/.*
  - https://ticketmaster.com
  - https://douban.com/
  - https://www.meetup.com/Linkerd-Online-Community-Meetup/events/260356731/
  - http://192.168.99.132:30969
DirectoryPath: public
