---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: default
data:
  nginx.conf: |-
    events {
    }
    http {
      include /etc/nginx/resolvers-data/resolvers.conf;
      server {
        location / {
          proxy_pass http://$http_host;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-gateway
  namespace: default
  labels:
    app: linkerd-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkerd-gateway
  template:
    metadata:
      labels:
        app: linkerd-gateway
    spec:
      volumes:
      - name: config
        configMap:
          name: nginx-configuration
      - name: resolvers-data
        emptyDir: {}    
      initContainers:
        - name: setup-resolvers
          image: busybox:1.28
          command: ["sh", "-c", "echo resolver $(awk 'BEGIN{ORS=\" \"} $1==\"nameserver\" {print $2}' /etc/resolv.conf)\";\" > /etc/nginx/resolvers-data/resolvers.conf"]
          volumeMounts:
            - name: resolvers-data
              mountPath: /etc/nginx/resolvers-data
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
          - name: config
            mountPath: /etc/nginx
          - name: resolvers-data
            mountPath: /etc/nginx/resolvers-data      
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-gateway
  namespace: default
  annotations: 
    mirror.linkerd.io/gateway-identity: default.default.serviceaccount.identity.linkerd.cluster.local
spec:
  ports:
  - name: incoming-port
    port: 80
    protocol: TCP
  selector:
    app: linkerd-gateway
  type: LoadBalancer